# Generated by Django 2.0.5 on 2018-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='討論主題')),
                ('content', models.TextField(verbose_name='討論內容')),
                ('poster', models.CharField(max_length=20, verbose_name='發表人')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('reply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
