# Generated by Django 2.0.5 on 2018-05-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(default=0)),
                ('content', models.TextField(verbose_name='回覆內容')),
                ('poster', models.CharField(max_length=20, verbose_name='發起人')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='poster',
            field=models.CharField(max_length=20, verbose_name='發起人'),
        ),
    ]
