# Generated by Django 2.0.5 on 2018-06-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180524_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
